version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: api
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./carga.sql:/docker-entrypoint-initdb.d/carga.sql

  app:
    build: .
    container_name: nodejs_app
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=1234
      - DB_NAME=api
    ports:
      - "4040:3001"
    depends_on:
      - db

volumes:
  db_data: